# Generated by Django 4.1.1 on 2022-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
