# Generated by Django 4.1.1 on 2022-11-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_initial"),
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="from_who",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="to_a_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.group"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="to_who",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
