# Generated by Django 4.1.1 on 2022-11-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("balances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="balances", to="groups.group"
            ),
        ),
    ]
