# Generated by Django 4.1.1 on 2022-11-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0014_rename_users_group_invited_users"),
        ("balances", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="for_groups",
            field=models.ManyToManyField(related_name="balances", to="groups.group"),
        ),
    ]
