# Generated by Django 4.1.1 on 2022-11-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0003_balance_for_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance",
            old_name="for_groups",
            new_name="groups",
        ),
    ]
