# Generated by Django 4.1.1 on 2022-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancecurrency",
            name="currency_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="balancecurrency",
            name="official_rate",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancecurrency",
            name="codename",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
