# Generated by Django 4.1.1 on 2022-11-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0004_balancecurrency_currency_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancecurrency",
            name="currency_id",
        ),
        migrations.RemoveField(
            model_name="balancecurrency",
            name="official_rate",
        ),
    ]
