# Generated by Django 4.1.1 on 2022-12-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0005_remove_balancecurrency_currency_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancecurrency",
            name="rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
        migrations.AddField(
            model_name="balancecurrency",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
