# Generated by Django 4.1.1 on 2022-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0006_alter_balance_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="pub_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
