# Generated by Django 4.1.1 on 2022-12-21 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0008_alter_currency_options_alter_currency_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2022, 12, 21, 12, 23, 46, 258440, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
