# Generated by Django 4.1.1 on 2022-12-22 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0009_alter_balance_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2022, 12, 22, 8, 20, 22, 133875, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
