# Generated by Django 4.1.1 on 2022-12-27 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0010_alter_balance_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="groups",
        ),
        migrations.AlterField(
            model_name="balance",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2022, 12, 27, 8, 59, 42, 5963, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
