# Generated by Django 4.1.1 on 2022-10-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "codename",
                    models.CharField(
                        choices=[
                            ("Test permission №1", "t_perm_1"),
                            ("Test permission №1", "t_perm_2"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
