# Generated by Django 4.1.1 on 2022-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(choices=[('owner', 'Owner'), ('read', 'User can read data'), ('edit', 'User can write data')], max_length=255),
        ),
    ]
