# Generated by Django 4.1.1 on 2022-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(choices=[('t_perm_1', 'Test permission №1'), ('t_perm_2', 'Test permission №2')], max_length=255),
        ),
    ]
