# Generated by Django 4.1.1 on 2022-10-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permission_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(choices=[('read', 'User can read data'), ('edit', 'User can write data')], max_length=255),
        ),
    ]
