# Generated by Django 4.1.1 on 2022-10-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "type",
                    models.CharField(
                        choices=[("cash", "Cash"), ("iban", "Bank account")],
                        max_length=255,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("BYN", "Belorussian (BYN)"),
                            ("RUS", "Russian (RUS)"),
                            ("USD", "American Dollar (USD)"),
                            ("EUR", "Euro (EUR)"),
                            ("CNY", "Chinese yan (CNY)"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
