# Generated by Django 4.1.1 on 2022-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
