# Generated by Django 4.1.1 on 2022-10-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0002_balance_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance",
            old_name="user",
            new_name="users",
        ),
    ]
