# Generated by Django 4.1.1 on 2022-10-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0003_rename_user_balance_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="users",
        ),
    ]
