# Generated by Django 4.1.1 on 2022-12-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0011_remove_balance_groups_alter_balance_created_at"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="balances",
            field=models.ManyToManyField(
                blank=True, related_name="user_groups", to="balances.balance"
            ),
        ),
    ]
