# Generated by Django 4.1.1 on 2022-10-27 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0010_alter_permission_codename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="permissions",
            field=models.ManyToManyField(
                related_name="user_groups", to="groups.permission"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(
                related_name="user_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
