# Generated by Django 4.1.1 on 2022-11-02 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0012_groupinformation_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupinformation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
