# Generated by Django 4.1.1 on 2022-11-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0013_alter_groupinformation_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="users",
            new_name="invited_users",
        ),
    ]
