# Generated by Django 4.1.1 on 2022-11-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0014_rename_users_group_invited_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="pub_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
