# Generated by Django 4.1.1 on 2022-11-08 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0016_alter_group_pub_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="invited_users",
            field=models.ManyToManyField(
                blank=True, related_name="user_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="user_groups", to="groups.permission"
            ),
        ),
    ]
