# Generated by Django 4.1.1 on 2022-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0017_alter_group_invited_users_alter_group_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupinformation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupinformation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
