# Generated by Django 4.1.1 on 2022-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0019_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="pub_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
