# Generated by Django 4.1.1 on 2022-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0020_invitation_pub_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="pub_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
