# Generated by Django 4.1.1 on 2022-11-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0024_remove_group_permissions_delete_permission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
