# Generated by Django 4.1.1 on 2022-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("required", "Required"), ("optional", "Optional")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="TransactionCategoryType",
        ),
    ]
