# Generated by Django 4.1.1 on 2022-10-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transactioncategory_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
    ]
