# Generated by Django 4.1.1 on 2022-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_remove_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="expense",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="income",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
    ]
