# Generated by Django 4.1.1 on 2022-12-27 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2022, 12, 27, 8, 59, 42, 6862, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
