# Generated by Django 4.1.1 on 2023-01-11 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2023, 1, 11, 7, 47, 26, 99381, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
