# Generated by Django 4.1.1 on 2022-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_transaction_who_made"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("income", "Income"), ("expense", "Expense")],
                max_length=255,
                null=True,
            ),
        ),
    ]
