# Generated by Django 4.1.1 on 2022-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_rename_expense_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=7, default=0, max_digits=19),
        ),
    ]
