# Generated by Django 4.1.1 on 2022-10-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppermission",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="group",
            name="group_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.groupinformation",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="group_permissions",
            field=models.ManyToManyField(to="groups.grouppermission"),
        ),
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
