# Generated by Django 4.1.1 on 2022-10-13 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
        ('permissions', '0002_alter_permission_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='group',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='group',
            name='balance',
            field=models.ManyToManyField(to='balance.balance'),
        ),
        migrations.AddField(
            model_name='group',
            name='permission',
            field=models.ManyToManyField(to='permissions.permission'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
