# Generated by Django 4.1.1 on 2022-10-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_balance_remove_group_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_id',
            new_name='group',
        ),
    ]
