# Generated by Django 4.1.1 on 2022-10-24 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupPermission',
            new_name='Permission',
        ),
    ]
