# Generated by Django 4.1.1 on 2022-10-12 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permission_codename'),
        ('balance', '0004_remove_balance_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='group',
            name='balances',
        ),
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.AddField(
            model_name='group',
            name='balances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='balance.balance'),
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.permission'),
        ),
    ]
