# Generated by Django 4.1.1 on 2022-10-24 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0003_rename_grouppermission_permission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Permission",
            new_name="GroupPermission",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="group_permissions",
            new_name="permissions",
        ),
    ]
