# Generated by Django 4.1.1 on 2022-10-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_group_id_group_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupID',
            new_name='GroupDescription',
        ),
    ]
