# Generated by Django 4.1.1 on 2022-10-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_users_group_user_remove_group_balances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='balances',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='permissions',
            new_name='permission',
        ),
    ]
