# Generated by Django 4.1.1 on 2022-10-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_groupid_groupdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='group_description',
        ),
    ]
