# Generated by Django 4.1.1 on 2022-10-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_rename_group_group_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
