# Generated by Django 4.1.1 on 2022-10-25 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0008_alter_permission_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
