# Generated by Django 4.1.1 on 2022-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0009_alter_permission_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="codename",
            field=models.CharField(max_length=255),
        ),
    ]
