# Generated by Django 4.1.1 on 2022-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="date_from",
        ),
        migrations.RemoveField(
            model_name="report",
            name="date_to",
        ),
        migrations.AddField(
            model_name="report",
            name="difference",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="total",
            field=models.DecimalField(decimal_places=7, max_digits=19),
        ),
    ]
