# Generated by Django 4.1.1 on 2023-01-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_report_date_from_remove_report_date_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="difference",
        ),
    ]
