# Generated by Django 4.1.1 on 2022-11-18 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0024_remove_group_permissions_delete_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("permissions", "0002_alter_permissiontype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
