# Generated by Django 4.1.1 on 2022-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_alter_permissiontype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="types",
            field=models.ManyToManyField(blank=True, to="permissions.permissiontype"),
        ),
    ]
